### ISSUE TITLE
Using workspace variables in workspace members causes dioxus-cli to panic

### ISSUE THREAD

**Issue by pascalbehmenburg** [DioxusLabs/dioxus#1526]
**Problem**

When using dioxus-cli in a workspace with workspace-wide variables defined in Cargo.toml that are being reused in workspace member Cargo.toml files it seems to cause dioxus-cli to panic with an rather unspecific ErrorInner.

**Steps To Reproduce**

- create a Cargo.toml file defining a workspace with at least one member which will be used as the dioxus root

Example:

```toml
[workspace]
members = ["dioxus-frontend"]

[workspace.package]
license = "MIT"
authors = ["Test author"]
```

- create a workspace member crate using `cargo new --bin dioxus-frontend`
- edit the Cargo.toml of this member crate to use the following variables:

```toml
[package]
name = "dioxus-frontend"
version = "0.1.0"
edition = "2021"
license.workspace = true
authors.workspace = true

[dependencies]
dioxus = "0.4.0"
dioxus-web = "0.4.0"
```
- I added the following contents to `main.rs`:

```rust
use dioxus::prelude::*;

fn main() {
  dioxus_web::launch(app);
}

fn app(cx: Scope) -> Element {
  cx.render(rsx! {
      div {
          "Hello Dioxus!"
      }
  })
}
```

- run `dx serve` (note: I ran it in the workspace member folder but I am not sure if this is required.)

**Expected behavior**

I expect dioxus to serve the web server on standard port serving me an html document with the specified div stating "Hello Dioxus!" in its contents.

**Backtrace**

Instead of a screenshot this might be more useful:

```rust
thread 'main' panicked at /Users/ambien/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-cli-0.4.1/src/config.rs:253:67:
called `Result::unwrap()` on an `Err` value: Parse(Error { inner: ErrorInner { kind: Custom, line: Some(4), col: 20, at: Some(83), message: "invalid type: map, expected a string", key: ["package", "license"] } })
stack backtrace:
   0:        0x10407d210 - std::backtrace_rs::backtrace::libunwind::trace::haef55eb0ea8d1d45
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10407d210 - std::backtrace_rs::backtrace::trace_unsynchronized::hed231663f16ef63f
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10407d210 - std::sys_common::backtrace::_print_fmt::h41733b2234a0a455
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10407d210 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h39ade40d5c2e560c
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x1040a2ad4 - core::fmt::rt::Argument::fmt::h91ed5f2b58c9facd
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/core/src/fmt/rt.rs:138:9
   5:        0x1040a2ad4 - core::fmt::write::h4dfa78425dc8960c
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/core/src/fmt/mod.rs:1114:21
   6:        0x104077ac0 - std::io::Write::write_fmt::h3de30f77c69d65cf
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/io/mod.rs:1760:15
   7:        0x10407d050 - std::sys_common::backtrace::_print::h28450b2437e1545d
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x10407d050 - std::sys_common::backtrace::print::hda9b914011de4269
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x10407e86c - std::panicking::default_hook::{{closure}}::hf48e15c0a2d132d0
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/panicking.rs:272:22
  10:        0x10407e584 - std::panicking::default_hook::h3c86fe3892269fcc
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/panicking.rs:292:9
  11:        0x10407edb0 - std::panicking::rust_panic_with_hook::h24acf85bffec9082
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/panicking.rs:731:13
  12:        0x10407ecb8 - std::panicking::begin_panic_handler::{{closure}}::h3b8025a3de8cd005
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/panicking.rs:609:13
  13:        0x10407d69c - std::sys_common::backtrace::__rust_end_short_backtrace::he38b9b0f6cc5da79
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/sys_common/backtrace.rs:170:18
  14:        0x10407ea24 - rust_begin_unwind
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/panicking.rs:597:5
  15:        0x104124fac - core::panicking::panic_fmt::hdd10bb28cef3e185
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/core/src/panicking.rs:72:14
  16:        0x104125304 - core::result::unwrap_failed::h844eed8bc4e367d1
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/core/src/result.rs:1652:5
  17:        0x10310157c - dioxus_cli::config::CrateConfig::new::hca924a2e30154a7e
  18:        0x102ff47f4 - dioxus_cli::cli::serve::Serve::serve::{{closure}}::haa833a3db08fcd57
  19:        0x10300e624 - tokio::runtime::park::CachedParkThread::block_on::h26ff35342c4d9694
  20:        0x10300f6d0 - tokio::runtime::context::runtime::enter_runtime::h60f897747153273b
  21:        0x102fd426c - tokio::runtime::runtime::Runtime::block_on::hff20b0ecbeac07f1
  22:        0x103016124 - dx::main::h31f5b5aede317fea
  23:        0x102f5b4c4 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd3258488eb18289e
  24:        0x102f70f30 - std::rt::lang_start::{{closure}}::h09169c54852147d6
  25:        0x10406f5ec - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h068cf96df06ba57c
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/core/src/ops/function.rs:284:13
  26:        0x10406f5ec - std::panicking::try::do_call::h7af00db0b6253f65
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/panicking.rs:504:40
  27:        0x10406f5ec - std::panicking::try::ha483118af72fc099
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/panicking.rs:468:19
  28:        0x10406f5ec - std::panic::catch_unwind::hc9687fee24f0301a
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/panic.rs:142:14
  29:        0x10406f5ec - std::rt::lang_start_internal::{{closure}}::hdd445e807d54aa0e
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/rt.rs:148:48
  30:        0x10406f5ec - std::panicking::try::do_call::h00c3db920e73bfe3
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/panicking.rs:504:40
  31:        0x10406f5ec - std::panicking::try::h2019a24c09ee2f01
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/panicking.rs:468:19
  32:        0x10406f5ec - std::panic::catch_unwind::ha9d88971b5da2c99
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/panic.rs:142:14
  33:        0x10406f5ec - std::rt::lang_start_internal::hce8bf24580c4573c
                               at /rustc/37390d65636dd67e263753a3c04fbc60dcc4348e/library/std/src/rt.rs:148:20
  34:        0x10301622c - _main
```

**Environment:**
 - Dioxus version: [v0.4, `master`]
 - Dioxus web version: [v0.4, `master`]
 - dioxus-cli version: [v0.4.1, `master`]
 - Rust version: [v1.74.0, `nightly`]
 - OS info: [MacOS]
 - App platform: [e.g. `web`, `desktop`]

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by pascalbehmenburg** [comment]
As I thought the issue seems to be in [config.rs:262](https://github.com/DioxusLabs/dioxus/blob/248d78fbfe859350fc9ac657e84264d984976c62/packages/cli/src/config.rs#L262). For now it seems to me that there is some problem with either the `cargo_toml` dependency or it is used in a way that causes the issue. I will try and figure out what could be a reasonable way to solve this.

![image](https://github.com/DioxusLabs/dioxus/assets/26353707/45aed36c-0e7b-49e4-b520-bfd3de720a4a)

**Comment by pascalbehmenburg** [comment]
Although the error wasn't to obvious it was a problem on my side. The compilation seems fine if the cargo.toml setup is correct. I had some additional workspace variables which required relative-paths instead of just setting them to `= true`. No need to bother any further.
