### ISSUE TITLE
`dx` perform long rebuilds until fast rebuilds take place; RA makes all rebuilds long (fullstack, Linux)

### ISSUE THREAD

**Issue by Andrew15-5** [DioxusLabs/dioxus#1862]
**Problem**

**Steps To Reproduce**

1. `git clone https://github.com/ealmloff/dioxus -b intigrate-collect-assets`
2. `cd dioxus`
3. install NASM (`nix profile install 'nixpkgs#nasm'`)
4. `cargo install --path ./packages/cli`
5. `dx create`
  <details><summary>answers</summary>

  ```
  [WARN] Favorite `gh:dioxuslabs/dioxus-template` not found in config, using it as a git repository: https://github.com/dioxuslabs/dioxus-template.git
  🤷   Project Name: fullstack
  [INFO] 🔧   Destination: /tmp/fullstack ...
  [INFO] 🔧   project-name: fullstack ...
  [INFO] 🔧   Generating template ...
  ✔ 🤷   What platform are you targeting? · Fullstack
  ✔ 🤷   Should the application use the dioxus router? · true
  ✔ 🤷   What backend framework are you using? · Axum
  ✔ 🤷   How do you want to create CSS? · Tailwind
  [INFO] 🔧   Moving generated files into: `/tmp/fullstack`...
  [INFO] 🔧   Initializing a fresh Git repository
  [INFO] ✨   Done! New project created /tmp/fullstack
  [INFO] Generated project at /tmp/fullstack
  ```

  </details>

6. `cd fullstack`
7. append this to `Cargo.toml`:
  ```toml
  [patch.crates-io]
  dioxus-fullstack = { git = "https://github.com/ealmloff/dioxus", branch = "intigrate-collect-assets" }
  dioxus = { git = "https://github.com/ealmloff/dioxus", branch = "intigrate-collect-assets" }
  dioxus-router = { git = "https://github.com/ealmloff/dioxus", branch = "intigrate-collect-assets" }
  # Dependent of dioxus-logger
  dioxus-core = { git = "https://github.com/ealmloff/dioxus", branch = "intigrate-collect-assets" }
  # dioxus-fullstack = { git = "https://github.com/ealmloff/dioxus", hash = "15dff7ad" }
  # dioxus = { git = "https://github.com/ealmloff/dioxus", hash = "15dff7ad" }
  # dioxus-router = { git = "https://github.com/ealmloff/dioxus", hash = "15dff7ad" }
  # # Dependent of dioxus-logger
  # dioxus-core = { git = "https://github.com/ealmloff/dioxus", hash = "15dff7ad" }
  ```
8. add `index.html`:
  ```html
  <!doctype html>
  <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="stylesheet" href="/tailwind.css">
      <title>Title</title>
    </head>
    <body>
      <div id="main"></div>
    </body>
  </html>
  ```
9. replace content of `cx.render(rsx!{})` in `Home()` in `src/main.rs` with:
  ```rs
          div {
              class: "w-10 h-10 bg-red-500",
              "test"
          }
  ```
10. run `tailwindcss -w -i input.css -o public/tailwind.css` in PWD
11. run `dx serve --platform fullstack --hot-reload` in PWD
12. open `src/main.rs` in editor without auto-save and without rust-analyzer
13. Try changing Tailwind classes and see how long the rebuilds and hot reloading will be:
  ```
  w-10 h-10 -> w-44 h-44
  w-44 h-44 -> w-40 h-40
  bg-red-500 -> bg-green-500
  bg-green-500 -> bg-blue-500
  bg-blue-500 -> bg-yellow-500
  bg-yellow-500 -> bg-red-50
  bg-red-50 -> bg-red-100
  bg-red-100 -> bg-red-200
  bg-red-200 -> bg-red-300
  bg-red-300 -> bg-red-400
  ```
14. after rebuilds are sub 10 seconds try throwing rust-analyzer into the mix (open the main file in editor, which will run rust-analyzer LSP server; I'm using Neovim + lazy.nvim + `mrcjkb/rustaceanvim`)
15. wait for RA to be ready
16. continue changing Tailwind classes, the rebuild times should now be much longer
17. if RA is not used, then rebuilds again should be sub 10 seconds

I run tests with 2 `dx` versions (also changed `[patch.crates-io]` in `Cargo.toml`) and here is how many super long compilations I had to wait until sub 10 seconds compilations start to appear:
1. (15dff7ad) 1st build + 5 rebuilds
2. (latest) 1st build + 3 rebuilds
3. (latest) 1st build + 1 rebuild
4. (15dff7ad) 1st build + 1 rebuild
5. (15dff7ad) 1st build + 1 rebuild
6. (latest) 1st build + 1 rebuild

Here are some logs of all 6 tests (RA is not used unless said otherwise; also sometimes there is a compilation order note):

<details><summary>logs</summary>

<details><summary>test 1 logs</summary>

```
-1------------------------------------------------------------------------------
[INFO] 🚅 Running build [Desktop] command...
\ 💼 Waiting to start build the project...                                                              [INFO] 🚅 Running build command...
\ ⚙ Compiling reqwest 0.11.23 (registry+https://github.com/rust-lang/crates.io-index)
/ ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)                                              \ ⚙ Compiling reqwest 0.11.23 (registry+https://github.com/rust-lang/crates.io-index)
[WARN] in name section: index `0` is out of bounds for data
[WARN] in name section: index `1` is out of bounds for data
- ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)                                              [INFO] 👑 Build done.
[INFO] 🚩 Build completed: [./dist]
build desktop done
[INFO] 🚀 Starting development server...
Listening on 127.0.0.1:8080

Dioxus @ v0.4.1 [18:28:15]


        > Profile : Debug
        > Hot Reload : RSX
        > Index Template : Custom [index.html]
        > URL Rewrite [index_on_404] : False

        > Build Time Use : 45460 millis

[INFO] A perfect compilation!

[INFO] 🚀 Starting development server...
================================================================================
🔥 Hot Reload WebSocket connected
🔮 Finding updates since last compile...
finished
================================================================================
[INFO] dioxus_fullstack::render - Rebuilding vdom
[INFO] dioxus_fullstack::render - Suspense resolved
================================================================================
w-10 h-10 -> w-44 h-44
================================================================================
[INFO] 🚅 Running build [Desktop] command...
\ 💼 Waiting to start build the project...                                                              [INFO] 🚅 Running build command...
/ ⚙ Compiling serde_repr 0.1.18 (registry+https://github.com/rust-lang/crates.io-index)
\ ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)                                              / ⚙ Compiling serde_repr 0.1.18 (registry+https://github.com/rust-lang/crates.io-index)
[WARN] in name section: index `0` is out of bounds for data
[WARN] in name section: index `1` is out of bounds for data
| ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)                                              [INFO] 👑 Build done.
[INFO] 🚩 Build completed: [./dist]
build desktop done
Listening on 127.0.0.1:8080

Project Reloaded: Changed 1 files. [18:32:34]


        > Profile : Debug
        > Hot Reload : RSX
        > Index Template : Custom [index.html]
        > URL Rewrite [index_on_404] : False

        > Build Time Use : 92224 millis

[INFO] A perfect compilation!

================================================================================
[INFO] dioxus_fullstack::render - Rebuilding vdom
[INFO] dioxus_fullstack::render - Suspense resolved
spinning up hot reloading
hot reloading ready
🔥 Hot Reload WebSocket connected
🔮 Finding updates since last compile...
finished
Connected to hot reloading 🚀
================================================================================
w-44 h-44 -> w-40 h-40
================================================================================
> Build Time Use : 83963 millis
================================================================================
bg-red-500 -> bg-green-500
================================================================================
> Build Time Use : 82377 millis
================================================================================
bg-green-500 -> bg-blue-500
================================================================================
> Build Time Use : 38014 millis
================================================================================
bg-blue-500 -> bg-yellow-500
================================================================================
> Build Time Use : 86491 millis
================================================================================
bg-yellow-500 -> bg-red-50
================================================================================
> Build Time Use : 2655 millis
================================================================================
bg-red-50 -> bg-red-100
================================================================================
> Build Time Use : 2471 millis
================================================================================
bg-red-100 -> bg-red-200
================================================================================
> Build Time Use : 2491 millis
================================================================================
bg-red-200 -> bg-red-300
================================================================================
> Build Time Use : 3384 millis
================================================================================
bg-red-300 -> bg-red-400
================================================================================
> Build Time Use : 3384 millis
--------------------------------------------------------------------------------
```

</details>

<details><summary>test 2 logs</summary>

```
-2------------------------------------------------------------------------------
$ dx serve --platform fullstack --hot-reload
[INFO] 🚅 Running build [Desktop] command...
- 💼 Waiting to start build the project...                                                              [INFO] 🚅 Running build command...
| ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)
| ⚙ Compiling dioxus-fullstack 0.4.3 (git+https://github.com/ealmloff/dioxus?branch=intigrate-collect-as\ ⚙ Compiling dioxus-fullstack 0.4.3 (git+https://github.com/ealmloff/dioxus?branch=intigrate-collect-as
[INFO] 🚩 Build completed: [./dist]
build desktop done
[INFO] 🚀 Starting development server...
- ⚙ Compiling dioxus-fullstack 0.4.3 (git+https://github.com/ealmloff/dioxus?branch=intigrate-collect-as
Dioxus @ v0.4.1 [19:06:03]


        > Profile : Debug
        > Hot Reload : RSX
        > Index Template : Custom [index.html]
        > URL Rewrite [index_on_404] : False

        > Build Time Use : 129142 millis

[INFO] A perfect compilation!

Listening on 127.0.0.1:8080
thread 'main' panicked at /home/user/.cargo/git/checkouts/dioxus-5df58c476196bcfb/785b61a/packages/ful
lstack/src/serve_config.rs:117:37:
Failed to find index.html. Make sure the index_path is set correctly and the WASM application has been b
uilt.: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
/ ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)
[INFO] 👑 Build done.
[WARN] in name section: index `0` is out of bounds for data
[WARN] in name section: index `1` is out of bounds for data
[INFO] 🚀 Starting development server...
================================================================================
$ dx serve --platform fullstack --hot-reload
[INFO] 🚅 Running build [Desktop] command...
\ 💼 Waiting to start build the project...                                                              [INFO] 🚅 Running build command...
- ⚙ Compiling fnv 1.0.7 (registry+https://github.com/rust-lang/crates.io-index)
| 💼 Waiting to start build the project...                                                              - 💼 Waiting to start build the project...
[INFO] 🚩 Build completed: [./dist]
build desktop done
[INFO] 🚀 Starting development server...

Dioxus @ v0.4.1 [19:07:50]


        > Profile : Debug
        > Hot Reload : RSX
        > Index Template : Custom [index.html]
        > URL Rewrite [index_on_404] : False

        > Build Time Use : 843 millis

[INFO] A perfect compilation!

Listening on 127.0.0.1:8080
- ⚙ Compiling libc 0.2.152 (registry+https://github.com/rust-lang/crates.io-index)
[INFO] 👑 Build done.
[WARN] in name section: index `0` is out of bounds for data
[WARN] in name section: index `1` is out of bounds for data
[INFO] 🚀 Starting development server...
[INFO] dioxus_fullstack::render - Rebuilding vdom
[INFO] dioxus_fullstack::render - Suspense resolved
spinning up hot reloading
hot reloading ready
Connected to hot reloading 🚀
🔥 Hot Reload WebSocket connected
🔮 Finding updates since last compile...
finished
================================================================================
w-10 h-10 -> w-44 h-44
================================================================================
[INFO] 🚅 Running build [Desktop] command...
- 💼 Waiting to start build the project...                                                              [INFO] 🚅 Running build command...
- ⚙ Compiling rand_chacha 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)
/ ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)                                              - ⚙ Compiling rand_chacha 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)
[WARN] in name section: index `0` is out of bounds for data
[WARN] in name section: index `1` is out of bounds for data
/ ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)                                              [INFO] 👑 Build done.
[INFO] 🚩 Build completed: [./dist]
build desktop done
Listening on 127.0.0.1:8080

Project Reloaded: Changed 1 files. [19:13:06]


        > Profile : Debug
        > Hot Reload : RSX
        > Index Template : Custom [index.html]
        > URL Rewrite [index_on_404] : False

        > Build Time Use : 217057 millis

[INFO] A perfect compilation!

[INFO] 🚅 Running build [Desktop] command...
\ 💼 Waiting to start build the project...
[INFO] 🚅 Running build command...
/ ⚙ Compiling tokio 1.35.1 (registry+https://github.com/rust-lang/crates.io-index)
\ ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)
/ ⚙ Compiling futures-lite 2.2.0 (registry+https://github.com/rust-lang/crates.io-index)
[WARN] in name section: index `0` is out of bounds for data
[WARN] in name section: index `1` is out of bounds for data
| ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)
[INFO] 👑 Build done.
[INFO] 🚩 Build completed: [./dist]
build desktop done
Listening on 127.0.0.1:8080

Project Reloaded: Changed 1 files. [19:16:48]


        > Profile : Debug
        > Hot Reload : RSX
        > Index Template : Custom [index.html]
        > URL Rewrite [index_on_404] : False

        > Build Time Use : 222029 millis

[INFO] A perfect compilation!

[INFO] dioxus_fullstack::render - Rebuilding vdom
[INFO] dioxus_fullstack::render - Suspense resolved
spinning up hot reloading
hot reloading ready
🔥 Hot Reload WebSocket connected
🔮 Finding updates since last compile...
finished
Connected to hot reloading 🚀
================================================================================
w-44 h-44 -> w-40 h-40
================================================================================
> Build Time Use : 216854 millis
================================================================================
bg-red-500 -> bg-green-500
================================================================================
> Build Time Use : 5318 millis
================================================================================
bg-green-500 -> bg-blue-500
================================================================================
> Build Time Use : 4559 millis
--------------------------------------------------------------------------------
```

</details>

<details><summary>test 3 logs</summary>

```
-3------------------------------------------------------------------------------
> Build Time Use : 129582 millis
================================================================================
w-10 h-10 -> w-44 h-44
================================================================================
> Build Time Use : 216998 millis
================================================================================
w-44 h-44 -> w-40 h-40
================================================================================
> Build Time Use : 5392 millis
================================================================================
bg-red-500 -> bg-green-500
================================================================================
> Build Time Use : 4609 millis
================================================================================
bg-green-500 -> bg-blue-500
================================================================================
> Build Time Use : 4378 millis
--------------------------------------------------------------------------------
```

</details>

<details><summary>test 4 logs</summary>

```
-4------------------------------------------------------------------------------
> Build Time Use : 123376 millis
================================================================================
w-10 h-10 -> w-44 h-44
================================================================================
> Build Time Use : 199674 millis
================================================================================
w-44 h-44 -> w-40 h-40
================================================================================
> Build Time Use : 4740 millis
================================================================================
bg-red-500 -> bg-green-500
================================================================================
> Build Time Use : 4341 millis
================================================================================
bg-green-500 -> bg-blue-500
================================================================================
> Build Time Use : 4313 millis
--------------------------------------------------------------------------------
```

</details>

<details><summary>test 5 logs</summary>

```
-5------------------------------------------------------------------------------
> Build Time Use : 39845 millis
================================================================================
w-10 h-10 -> w-44 h-44
================================================================================
> Build Time Use : 80646 millis
================================================================================
w-44 h-44 -> w-40 h-40
================================================================================
> Build Time Use : 2503 millis
================================================================================
bg-red-500 -> bg-green-500
================================================================================
> Build Time Use : 2484 millis
================================================================================
bg-green-500 -> bg-blue-500
================================================================================
> Build Time Use : 2446 millis
================================================================================
RA is on
bg-blue-500 -> bg-yellow-500
================================================================================
> Build Time Use : 58934 millis
================================================================================
bg-yellow-500 -> bg-red-50
================================================================================
> Build Time Use : 56882 millis
================================================================================
bg-red-50 -> bg-red-100
================================================================================
client + RA, server
> Build Time Use : 69118 millis
================================================================================
bg-red-100 -> bg-red-200
================================================================================
client + RA, server
> Build Time Use : 70073 millis
================================================================================
bg-red-200 -> bg-red-300
================================================================================
client + RA, server
> Build Time Use : 68866 millis
================================================================================
bg-red-300 -> bg-red-400
================================================================================
client + RA, server
> Build Time Use : 69522 millis
--------------------------------------------------------------------------------
```

</details>

<details><summary>test 6 logs</summary>

```
-6------------------------------------------------------------------------------
> Build Time Use : 122749 millis
================================================================================
w-10 h-10 -> w-44 h-44
================================================================================
> Build Time Use : 206721 millis
================================================================================
w-44 h-44 -> w-40 h-40
================================================================================
> Build Time Use : 4878 millis
================================================================================
bg-red-500 -> bg-green-500
================================================================================
> Build Time Use : 4467 millis
================================================================================
bg-green-500 -> bg-blue-500
================================================================================
> Build Time Use : 4274 millis
================================================================================
RA is on
bg-blue-500 -> bg-yellow-500
================================================================================
> Build Time Use : 186793 millis
================================================================================
bg-yellow-500 -> bg-red-50
================================================================================
client, server, RA
> Build Time Use : 187481 millis
================================================================================
bg-red-50 -> bg-red-100
================================================================================
client, server, RA
> Build Time Use : 182991 millis
================================================================================
bg-red-100 -> bg-red-200
================================================================================
client + RA, server
> Build Time Use : 220144 millis
================================================================================
bg-red-200 -> bg-red-300
================================================================================
RA is off
> Build Time Use : 4818 millis
================================================================================
bg-red-300 -> bg-red-400
================================================================================
client + RA, server
> Build Time Use : 4064 millis
--------------------------------------------------------------------------------
```

</details>

</details>

In summary, rust-analyzer does affect the rebuild time in 100% cases, i.e., it makes rebuild as if they are "clean builds". The hot reloading time also increased from 1 or 2 seconds to 5 or 10 seconds (also, looks like the "clean rebuild" hot reloading time). Although last runs all took 1 build and 1 rebuild after which quick rebuild start to appear, but first runs include more rebuild, therefore, "long rebuild" counter is *random* (maybe some caching is present outside of the PWD that decreased the amount of "long rebuilds").

I don't know what to include into a container to make a portable environment and I don't know if it will be useful. Tested with editors without RA: Neovim, VSCodium — no difference in behavior.

**Environment:**
 - Dioxus version: `https://github.com/ealmloff/dioxus -b intigrate-collect-assets`
 - Rust version: nightly
 - OS info: Pop!_OS 22.04
 - App platform: fullstack

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
This issue also happens on ubuntu on the current git version of dioxus. I tried setting the ssr as a default feature with `rust-analyzer.cargo.features`, but that doesn't seems to help.

It looks like only the server rebuild is much longer. This makes sense because the web rebuild happens in an entirely different folder

Some things you could try to work towards fixing this issue:
- Try to reproduce this without the CLI. Does `cargo run --features ssr` also take much longer with RA?
- Try making ssr a default feature and see if that effects incremental compile times
- See exactly what crates are rebuilding with https://doc.rust-lang.org/cargo/reference/timings.html
- Try changing both `rust-analyzer.check.features` and `rust-analyzer.cargo.features`

If all else fails, you could change `rust-analyzer.checkOnSave` to false

**Comment by Andrew15-5** [comment]
What about the "long rebuilds" without RA? How much "1 clean build + ? long rebuilds" is needed for quick rebuilds to start showing up on other platforms? "1 + 1"?

>  Does `cargo run --features ssr` also take much longer with RA?

You mean running the same command manually after each edit?

> Try making ssr a default feature and see if that effects incremental compile times

In RA or cargo?

> See exactly what crates are rebuilding with https://doc.rust-lang.org/cargo/reference/timings.html

I bet all crates are rebuilding.

> If all else fails, you could change `rust-analyzer.checkOnSave` to false

Is this a "nothing we can do about it" solution, or is it a debugging step?

**Comment by ealmloff** [comment]
> What about the "long rebuilds" without RA? How much "1 clean build + ? long rebuilds" is needed for quick rebuilds to start showing up on other platforms? "1 + 1"?

On macos, it only takes one clean rebuild for incremental (short) builds to start.

> > Does cargo run --features ssr also take much longer with RA?
> You mean running the same command manually after each edit?

Yes, just for testing purposes. This seems more like a cargo/rust analyzer bug if anything. If you can reproduce it without dioxus and dioxus-cli, you could open an issue on one of those repos (probably rust-analyzer?).

> > Try making ssr a default feature and see if that effects incremental compile times
> In RA or cargo?

In your `cargo.toml`

> > If all else fails, you could change `rust-analyzer.checkOnSave` to false
> 
> Is this a "nothing we can do about it" solution, or is it a debugging step?

This would be a solution if we can't fix the issue.

**Comment by Andrew15-5** [comment]
> On macos, it only takes one clean rebuild for incremental (short) builds to start.

So this means that the problem is not only with RA, but also with `dx`/`cargo`, because for the most runs I didn't use RA, only `dx` and it always took more than just "1 clean build" to get those quick rebuilds.

> * Try to reproduce this without the CLI. Does `cargo run --features ssr` also take much longer with RA?

What about the client? How do I manually compile it, if it should be compiled in a separate dir? Do we just ignore it altogether (losing ability to check the result in a browser)?

**Comment by ealmloff** [comment]
> > * Try to reproduce this without the CLI. Does `cargo run --features ssr` also take much longer with RA?
> 
> What about the client? How do I manually compile it, if it should be compiled in a separate dir? Do we just ignore it altogether (losing ability to check the result in a browser)?

You can just ignore the resulting binary and only build the server. It looks like only the server build is slow, so we don't need to check the web feature

**Comment by Andrew15-5** [comment]
Ok then... I'll try to do the steps.

**Comment by ealmloff** [comment]
If it is specific to dioxus/dx, it could be related to https://github.com/DioxusLabs/dioxus/pull/1622 or some other environment variables we set.

If a package uses `env!("DIOXUS_CONFIG")` it will be recompiled when `DIOXUS_CONFIG` changes. Cargo might be recompiling it because we remove and reset some environment variables between builds. This is where timing information (with just cargo, or if it is specific to dioxus, in a fork of dioxus that adds the --timing arg) would be very useful

**Comment by Andrew15-5** [comment]
> * Try to reproduce this without the CLI. Does `cargo run --features ssr` also take much longer with RA?

> You can just ignore the resulting binary and only build the server.

`cargo run -F ssr`:

```
Listening on 127.0.0.1:8080
thread 'main' panicked at /home/user/.cargo/git/checkouts/dioxus-5df58c476196bcfb/785b61a/packages/fullstack/src/serve_config.rs:117:37:
Failed to find index.html. Make sure the index_path is set correctly and the WASM application has been built.: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`cargo run -F web`:

```
thread 'main' panicked at /home/user/.cargo/git/checkouts/dioxus-5df58c476196bcfb/785b61a/packages/fullstack/src/launch.rs:129:48:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ealmloff** [comment]
I wouldn't expect either one of them to run on their own. We are really just interested in the build time here so that doesn't matter. The CLI is doing something like `dx build --platform web` and then `cargo run --features ssr`.

> > * Try to reproduce this without the CLI. Does `cargo run --features ssr`
> 
> > You can just ignore the resulting binary and only build the server.
> 
> `cargo run -F ssr`:
> 
> ```
> Listening on 127.0.0.1:8080
> thread 'main' panicked at /home/user/.cargo/git/checkouts/dioxus-5df58c476196bcfb/785b61a/packages/fullstack/src/serve_config.rs:117:37:
> Failed to find index.html. Make sure the index_path is set correctly and the WASM application has been built.: Os { code: 2, kind: NotFound, message: "No such file or directory" }
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

If you try to run the server first, your server will not be able to find the client WASM and HTML to serve, so it will fail.

> ```
> 
> `cargo run -F web`:
> 
> ```
> thread 'main' panicked at /home/user/.cargo/git/checkouts/dioxus-5df58c476196bcfb/785b61a/packages/fullstack/src/launch.rs:129:48:
> called `Option::unwrap()` on a `None` value
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

You can't run the web code on the client. You can compile it with `cargo build --features web --target wasm32-unknown-unknown`, but you need to link it with the `wasm-bindgen-cli-support` crate which trunk and the dioxus CLI uses when serving for the web

**Comment by gramidt** [comment]
I'm also running into super long rebuild times when using the Dioxus CLI. I'm assuming I have something setup incorrectly, but I've spent the past few hours investigating with no luck. Unless someone has an idea, I'm planning to start grokking and debugging the code.

Details:
- Rust:   nightly-x86_64-apple-darwin unchanged - rustc 1.77.0-nightly (5bd5d214e 2024-01-25)
- DX CLI: 0.4.3 (fa933e35 2024-01-28)
- Macbook M1: (14.2.1)
- RA: Disabled on Save (`"rust-analyzer.checkOnSave": false`)
- Note: I was also experiencing this in a devcontainer, but removed that as a variable.

To help troubleshoot this, I set up a simple full-stack app that renders a single div with some text. When executing `dx serve --platform fullstack --hot-reload`, the first run takes ~50s. When updating the text within the div, it takes ~100s to recompile. If I stop the process and re-start it without cleaning artifacts, it takes about ~50s. 

First build:
<img width="420" alt="Screenshot 2024-01-28 at 3 19 29 PM" src="https://github.com/DioxusLabs/dioxus/assets/1246157/2efd3e34-fca9-4c60-b691-de5ab63be577">

Build after changing text within div:
<img width="448" alt="Screenshot 2024-01-28 at 3 21 39 PM" src="https://github.com/DioxusLabs/dioxus/assets/1246157/9ce01eb3-7504-4a73-9fa8-7d207917ce58">

Not changing anything, but just re-executing `dx serve --platform fullstack --hot-reload` after stopping the previous process.
<img width="434" alt="Screenshot 2024-01-28 at 3 23 49 PM" src="https://github.com/DioxusLabs/dioxus/assets/1246157/251485d5-ab86-4fd2-a291-fed44f6707b6">

When I try the same test, but if I use Dioxus CLI for web and use cargo directly for SSR (e.g., `dx serve --platform web` and `cargo run --features ssr`), the web finishes recompiling in < 3s, sometimes in ~400ms, and SSR in ~2s.

Reload after changing text within div:
<img width="525" alt="Screenshot 2024-01-28 at 3 29 57 PM" src="https://github.com/DioxusLabs/dioxus/assets/1246157/161c5e93-f233-4173-a8d0-7ac6a6ad20ed">

Build after changing text within div:
<img width="532" alt="Screenshot 2024-01-28 at 3 32 05 PM" src="https://github.com/DioxusLabs/dioxus/assets/1246157/5dd5c8ad-71d0-4ede-8c39-36f1d0341bd5">

**Comment by Andrew15-5** [comment]
@gramidt, try using `dx` without RA. If rebuilds are fast, then the problem is only with caching. In https://discord.com/channels/899851952891002890/1201227808060494025 we discovered that using something like `env CARGO_TARGET_DIR='.dioxus/ssr' RUSTFLAGS='-C opt-level=2 -C debug-assertions' cargo build -F ssr` solves the problem with RA, because now all 3 builds are in 3 separate directories. I'm currently trying to patch the `dx`'s code.

**Comment by gramidt** [comment]
Thank you for the prompt response. I sincerely appreciate it.

For this test, I had RA disabled. The times I was seeing, didn't appear to be waiting on the lock.

Am I glossing over something else that should be disabled?

**Comment by Andrew15-5** [comment]
If RA is out of the equation, then I have no idea. As I've written in the OP, the `dx` itself eventually does perform very fast rebuilds. Maybe @ealmloff can take a look at this later.

**Comment by gramidt** [comment]
Another interesting fact is that it "occasionally" performs super quick, sub 500ms; however, most of the time, it takes > 50s, regardless of the size of the change. In fact, I can make the exact change from the same starting state, and the time is inconsistent.

Since you're experiencing something different, I'm happy to dig into it and report on my findings.

**Comment by ealmloff** [comment]
Me and [Andrew15-5](https://github.com/Andrew15-5) have been discussing this issue more in this thread https://discord.com/channels/899851952891002890/1201227808060494025. Here is a summary:

Long rebuilds are caused by desktop builds with the same target directory as normal builds with different rustflags. `dx serve --platform fullstack` builds the server with opt-level 2 in the debug profile which overrides the RA cache. If RA runs again, it will override the fullstack server build cache causing a full rebuild most times. @Andrew15-5 is working on changing the target directory that fullstack uses which should fix this issue

**Comment by Andrew15-5** [comment]
But @gramidt is having issue with RA being disabled.

**Comment by gramidt** [comment]
Update: I ended up switching back to using `dx build --features web && dx serve --features ssr --hot-reload --platform desktop` versus `dx serve --platform fullstack`, but I plan on digging into the issue in the coming days.
