### ISSUE TITLE
Raw tokens (r#) as element names cause client-side panic on debug builds

### ISSUE THREAD

**Issue by david-boles** [DioxusLabs/dioxus#2904]
**Problem**

Client-side panic after opening a `fullstack` page served by `dx serve`:

```
specs.js:793 panicked at /home/deb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-web-0.5.6/src/mutations.rs:24:80:
called `Result::unwrap()` on an `Err` value: JsValue(InvalidCharacterError: Failed to execute 'createElementNS' on 'Document': The qualified name provided ('r#use') contains the invalid character '#'.
Error: Failed to execute 'createElementNS' on 'Document': The qualified name provided ('r#use') contains the invalid character '#'.
    at http://10.39.18.230:3000/assets/dioxus/specs.js:928:37
    at handleError (http://10.39.18.230:3000/assets/dioxus/specs.js:347:18)
    at imports.wbg.__wbg_createElementNS_556a62fb298be5a2 (http://10.39.18.230:3000/assets/dioxus/specs.js:927:78)
    at specs_standalone-b6b8bcbac76031b6.wasm.web_sys::features::gen_Document::Document::create_element_ns::h1e3ece09c7885e61 (http://10.39.18.230:3000/assets/dioxus/specs_bg.wasm:wasm-function[2917]:0x35dfc8)
    at specs_standalone-b6b8bcbac76031b6.wasm.dioxus_web::mutations::<impl dioxus_web::dom::WebsysDom>::create_template_node::hf605a3c62b524d7b (http://10.39.18.230:3000/assets/dioxus/specs_bg.wasm:wasm-function[597]:0x17aa7e)
    at specs_standalone-b6b8bcbac76031b6.wasm.dioxus_web::mutations::<impl dioxus_web::dom::WebsysDom>::create_template_node::hf605a3c62b524d7b (http://10.39.18.230:3000/assets/dioxus/specs_bg.wasm:wasm-function[597]:0x17ad73)
    at specs_standalone-b6b8bcbac76031b6.wasm.dioxus_web::mutations::<impl dioxus_core::mutations::WriteMutations for dioxus_web::dom::WebsysDom>::register_template::he73fa90e57606260 (http://10.39.18.230:3000/assets/dioxus/specs_bg.wasm:wasm-function[2463]:0x32accf)
    at specs_standalone-b6b8bcbac76031b6.wasm.dioxus_core::virtual_dom::VirtualDom::flush_templates::h952e5d784239a561 (http://10.39.18.230:3000/assets/dioxus/specs_bg.wasm:wasm-function[462]:0x126471)
    at specs_standalone-b6b8bcbac76031b6.wasm.dioxus_core::virtual_dom::VirtualDom::render_immediate::hdf41ae228a04e58c (http://10.39.18.230:3000/assets/dioxus/specs_bg.wasm:wasm-function[436]:0x1112de)
    at specs_standalone-b6b8bcbac76031b6.wasm.dioxus_web::run::{{closure}}::hc8be13591dfedcad (http://10.39.18.230:3000/assets/dioxus/specs_bg.wasm:wasm-function[283]:0x468b5))
```

**Steps To Reproduce**

- Version 0.5.6
- Include an element with a parameter named with a raw token:
  ```
  svg {
      r#use {
          href: "..."
      }
  }
  ```
- Launch with `dx serve`
- Observe panic in browser console.
- Re-launch with `dx serve --release`
- Observe no panic.

**Comment by ealmloff** [comment]
I cannot reproduce this issue with dioxus `0.6.0-alpha.2` with this code:
```toml
[dependencies]
dioxus = { version = "0.6.0-alpha.2", features = ["fullstack", "router"] }

[features]
web = ["dioxus/web"]
ssr = ["dioxus/server"]
```
```rust
#![allow(non_snake_case)]
use dioxus::prelude::*;


fn main() {
    launch(App);
}

fn App() -> Element {
    rsx! {
        svg {
            r#use {
            }
        }
    }
}
```

**Comment by david-boles** [comment]
Me neither :+1:

**Comment by mhfan** [comment]
This panic still occurs during hot-reloading for dioxus-v0.6.1, while not in 'dx serve' new run.

<img width="1163" alt="Image" src="https://github.com/user-attachments/assets/94e9980c-d0b5-462c-b29c-b20a9aeba37f" />
