### ISSUE TITLE
The "Open app" functionality of CLI is broken with fullstack web apps

### ISSUE THREAD

**Issue by ochrons** [DioxusLabs/dioxus#3295]
**Problem**

When running a fullstack web app using Dioxus CLI and pressing `o` "to open the app", the CLI starts another instance of the web server, which will fail immediately due to port conflict, resulting in infinite loop of app restarts.

**Steps To Reproduce**

- `dx serve` a fullstack web app
- Press `o`
- 

**Expected behavior**

For web apps I would expect this to open a browser tab with the server address.

**Environment:**
 - Dioxus version:  0.6.0-rc.0
 - Rust version:    1.83
 - OS info:         WSL
 - App platform:    Fullstack web

**Comment by ufoscout** [comment]
Same issue with `0.6.0`, it seems the problem is linked to the address already in use:

```
$ dx serve
20:37:42 [dev] -----------------------------------------------------------------                   
                Serving your Dioxus app: web 🚀
                • Press `ctrl+c` to exit the server
                • Press `r` to rebuild the app
                • Press `o` to open the app
                • Press `v` to toggle verbose logging
                • Press `/` for more commands and shortcuts
                Learn more at https://dioxuslabs.com/learn/0.6/getting_started
               ----------------------------------------------------------------                    
20:38:18 [dev] Build completed successfully in 33286ms, launching app! 💫
20:39:37 [dev] [200] /
20:39:54 [dev] [200] /
20:39:59 [server] thread 'main' panicked at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-fullstack-0.6.0/src/server/launch.rs:104:73
20:39:59 [server] called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" 
20:39:59 [server] stack backtrace:
20:39:59 [server]    0: rust_begin_unwind
20:39:59 [server]              at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:
20:39:59 [server]    1: core::panicking::panic_fmt
20:39:59 [server]              at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:1
20:39:59 [server]    2: core::result::unwrap_failed
20:39:59 [server]              at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/result.rs:1700:
20:39:59 [server]    3: core::result::Result<T,E>::unwrap
20:39:59 [server]              at /home/ufo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1104:2
20:39:59 [server]    4: dioxus_fullstack::server::launch::launch::{{closure}}
20:39:59 [server]              at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-fullstack-0.6.0/src/server/launch.rs:104:2
20:39:59 [server]    5: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
20:39:59 [server]              at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/park.rs:281:6
20:39:59 [server]    6: tokio::runtime::coop::with_budget
20:39:59 [server]              at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/coop.rs:107:
20:39:59 [server]    7: tokio::runtime::coop::budget
20:39:59 [server]              at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/coop.rs:73:
20:39:59 [server]    8: tokio::runtime::park::CachedParkThread::block_on
20:39:59 [dev] Application [server] exited with error: exit status: 101
20:39:59 [server]              at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/park.rs:281:3
20:39:59 [dev] Application [server] exited with error: exit status: 101
20:39:59 [server]    9: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
20:39:59 [dev] Application [server] exited with error: exit status: 101
20:40:00 [server]              at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/context/blocking.rs:66:
20:40:00 [server]   10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
20:40:00 [server]              at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/multi_thread/mod.rs:87:1
20:40:00 [server]   11: tokio::runtime::context::runtime::enter_runtime
20:40:00 [dev] Application [server] exited with error: exit status: 101
20:40:00 [server]              at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/context/runtime.rs:65:1
20:40:00 [server]   12: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
20:40:00 [server]              at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/multi_thread/mod.rs:86:
20:40:00 [server]   13: tokio::runtime::runtime::Runtime::block_on_inner
20:40:00 [server]              at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/runtime.rs:370:4
20:40:00 [server]   14: tokio::runtime::runtime::Runtime::block_on
20:40:00 [server]              at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/runtime.rs:342:1
20:40:00 [server]   15: dioxus_fullstack::server::launch::launch
20:40:00 [dev] Application [server] exited with error: exit status: 101
20:40:00 [server]              at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-fullstack-0.6.0/src/server/launch.rs:25:
20:40:00 [server]   16: dioxus::launch::LaunchBuilder::new::{{closure}}
20:40:00 [dev] Application [server] exited with error: exit status: 101
20:40:00 [server]              at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-0.6.0/src/launch.rs:44:4
20:40:00 [dev] Application [server] exited with error: exit status: 101
20:40:00 [server]   17: core::ops::function::FnOnce::call_once
20:40:00 [server]              at /home/ufo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:
20:40:00 [server]   18: dioxus::launch::LaunchBuilder::launch_inner
20:40:00 [server]              at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-0.6.0/src/launch.rs:181:
20:40:00 [server]   19: dioxus::launch::LaunchBuilder::launch
20:40:00 [server]              at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-0.6.0/src/launch.rs:186:
20:40:00 [server]   20: dioxus::launch::launch
20:40:00 [server]              at /home/ufo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-0.6.0/src/launch.rs:262:
20:40:00 [server]   21: web::main
20:40:00 [server]              at ./src/main.rs:22:5
20:40:00 [server]   22: core::ops::function::FnOnce::call_once
20:40:00 [dev] Application [server] exited with error: exit status: 101
20:40:00 [server]              at /home/ufo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:
20:40:00 [dev] Application [server] exited with error: exit status: 101
20:40:00 [dev] Application [server] exited with error: exit status: 101
20:40:00 [server] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace
20:40:00 [dev] Application [server] exited with error: exit status: 101
20:40:00 [dev] Application [server] exited with error: exit status: 101
20:40:00 [dev] Application [server] exited with error: exit status: 101
20:40:00 [dev] Application [server] exited with error: exit status: 101
```
