### ISSUE TITLE
panic in TextRenderer

### ISSUE THREAD

**Issue by tv42** [DioxusLabs/dioxus#609]
**Problem**

I tried to make a component that outputs raw HTML (see https://github.com/DioxusLabs/dioxus/issues/608).
I managed to trigger a panic:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/tv/.cargo/registry/src/github.com-1ecc6299db9ec823/dioxus-ssr-0.2.1/src/lib.rs:276:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/option.rs:775:21
   4: dioxus_ssr::TextRenderer::html_render
             at /home/tv/.cargo/registry/src/github.com-1ecc6299db9ec823/dioxus-ssr-0.2.1/src/lib.rs:276:27
   5: dioxus_ssr::TextRenderer::html_render
             at /home/tv/.cargo/registry/src/github.com-1ecc6299db9ec823/dioxus-ssr-0.2.1/src/lib.rs:272:21
   6: <dioxus_ssr::TextRenderer as core::fmt::Display>::fmt
             at /home/tv/.cargo/registry/src/github.com-1ecc6299db9ec823/dioxus-ssr-0.2.1/src/lib.rs:126:9
   7: core::fmt::write
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
   8: core::fmt::Write::write_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:188:9
   9: alloc::fmt::format::format_inner
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/fmt.rs:612:9
  10: alloc::fmt::format::{{closure}}
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/fmt.rs:616:34
  11: core::option::Option<T>::map_or_else
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/option.rs:1023:21
  12: alloc::fmt::format
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/fmt.rs:616:5
  13: dioxus_ssr::render_lazy
             at /home/tv/.cargo/registry/src/github.com-1ecc6299db9ec823/dioxus-ssr-0.2.1/src/lib.rs:60:5
  14: one::main
             at ./src/bin/one.rs:12:9
  15: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Steps To Reproduce**

attempt 1:

```
use dioxus::prelude::*;

fn Doctype(cx: Scope<()>) -> Element {
    let factory = NodeFactory::new(&cx);
    let element = factory.raw_element("!DOCTYPE", None, &[], &[], &[], None);
    Some(element)
}

fn main() {
    println!(
        "{}",
        dioxus::ssr::render_lazy(rsx! {
            Doctype {},
            h1 { "Hello, world!" }
        }),
    );
}
```

attempt 2:

```
use dioxus::prelude::*;

fn Doctype(cx: Scope<()>) -> Element {
    let element =
        LazyNodes::new(|factory| factory.raw_element("!DOCTYPE", None, &[], &[], &[], None));
    cx.render(element)
}

fn main() {
    println!(
        "{}",
        dioxus::ssr::render_lazy(rsx! {
            Doctype {},
            h1 { "Hello, world!" }
        }),
    );
}
```

Regardless of how wrong I'm using the APIs, the panic seems undesirable.

**Environment:**
 - Dioxus version: 0.2.4
 - Rust version: 1.64.0
 - OS info: Linux/NixOS
 - App platform: web / ssr

**Comment by Demonthos** [comment]
Currently the VirtualDom needs to be created and built before it is rendered with ssr in order to work with components. See the [ssr](https://github.com/DioxusLabs/dioxus/blob/master/examples/ssr.rs) example.
There is a PR that makes render lazy work with components: https://github.com/DioxusLabs/dioxus/pull/355

**Comment by tv42** [comment]
Ah, this worked (for values of "worked" that mean "didn't crash, produced output"; it's not the output I wanted, still, but that's #608):

```
use dioxus::prelude::*;

fn Doctype(cx: Scope) -> Element {
    let element =
        LazyNodes::new(|factory| factory.raw_element("!DOCTYPE", None, &[], &[], &[], None));
    cx.render(element)
}

fn App(cx: Scope) -> Element {
    cx.render(rsx! {
        Doctype {},
        h1 { "Hello, world!" }
    })
}

fn main() {
    let mut vdom = VirtualDom::new(App);
    let _ = vdom.rebuild();
    println!("{}", dioxus::ssr::render_vdom(&vdom));
}
```
